import React, { useState, useEffect } from "react";
import { apiClient } from "../../api/client";
import {
  ShieldCheck,
  KeyRound,
  QrCode,
  Copy,
  Check,
  X,
  AlertCircle,
  CheckCircle2,
  Lock,
  LifeBuoy,
} from "lucide-react";

interface MfaAuthModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: () => void;
}

type MfaTab = "verify" | "setup" | "recovery";

export const MfaAuthModal: React.FC<MfaAuthModalProps> = ({ isOpen, onClose, onSuccess }) => {
  const [activeTab, setActiveTab] = useState<MfaTab>("verify");
  const [totpCode, setTotpCode] = useState<string>("");
  const [recoveryCode, setRecoveryCode] = useState<string>("");

  // Setup state
  const [setupData, setSetupData] = useState<{ secret: string; provisioning_uri: string } | null>(null);
  const [setupVerificationCode, setSetupVerificationCode] = useState<string>("");
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);

  // Feedback
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);
  const [copiedSecret, setCopiedSecret] = useState<boolean>(false);

  useEffect(() => {
    if (!isOpen) {
      setError(null);
      setSuccessMsg(null);
      setTotpCode("");
      setRecoveryCode("");
    }
  }, [isOpen]);

  const handleStartSetup = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await apiClient.setupTotp();
      setSetupData(res);
      setActiveTab("setup");
    } catch (err: any) {
      setError(err.message || "Failed to initialize TOTP secret");
    } finally {
      setLoading(false);
    }
  };

  const handleVerifyTotp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (totpCode.length !== 6) {
      setError("Please enter a valid 6-digit TOTP verification code.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      await apiClient.verifyTotp(totpCode);
      setSuccessMsg("MFA Step-Up Verified Successfully!");
      setTimeout(() => {
        onSuccess?.();
        onClose();
      }, 1200);
    } catch (err: any) {
      setError(err.message || "Invalid or expired TOTP code.");
    } finally {
      setLoading(false);
    }
  };

  const handleActivateTotp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (setupVerificationCode.length !== 6) {
      setError("Please enter the 6-digit code generated by your authenticator app.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await apiClient.activateTotp(setupVerificationCode);
      setRecoveryCodes(res.recovery_codes || []);
      setSuccessMsg("TOTP Authenticator successfully activated! Save your recovery codes.");
    } catch (err: any) {
      setError(err.message || "Failed to activate TOTP authenticator.");
    } finally {
      setLoading(false);
    }
  };

  const handleConsumeRecovery = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!recoveryCode.trim()) {
      setError("Please enter your emergency single-use recovery code.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await apiClient.consumeRecoveryCode(recoveryCode);
      setSuccessMsg(`Emergency recovery code accepted! Remaining backup codes: ${res.remaining_codes_count}`);
      setTimeout(() => {
        onSuccess?.();
        onClose();
      }, 1400);
    } catch (err: any) {
      setError(err.message || "Invalid or already consumed recovery code.");
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="mfa-modal-title"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm"
    >
      <div className="relative w-full max-w-lg bg-slate-900 border-2 border-indigo-500/40 rounded-2xl shadow-2xl p-6 text-slate-100 space-y-5">
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-indigo-600/20 border border-indigo-500/30 text-indigo-400">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h2 id="mfa-modal-title" className="text-base font-bold text-slate-100">
                Multi-Factor Security Center
              </h2>
              <p className="text-[11px] text-slate-400 font-mono">RFC 6238 TOTP &bull; SHA-256 Recovery Codes</p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close dialog"
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab Controls */}
        <div className="flex border-b border-slate-800 text-xs">
          <button
            type="button"
            onClick={() => setActiveTab("verify")}
            className={`flex items-center gap-1.5 px-4 py-2 font-semibold border-b-2 transition ${
              activeTab === "verify"
                ? "border-indigo-500 text-indigo-400"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <KeyRound className="w-3.5 h-3.5" />
            Step-Up Verify
          </button>
          <button
            type="button"
            onClick={handleStartSetup}
            className={`flex items-center gap-1.5 px-4 py-2 font-semibold border-b-2 transition ${
              activeTab === "setup"
                ? "border-indigo-500 text-indigo-400"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <QrCode className="w-3.5 h-3.5" />
            Enroll App
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("recovery")}
            className={`flex items-center gap-1.5 px-4 py-2 font-semibold border-b-2 transition ${
              activeTab === "recovery"
                ? "border-indigo-500 text-indigo-400"
                : "border-transparent text-slate-400 hover:text-slate-200"
            }`}
          >
            <LifeBuoy className="w-3.5 h-3.5" />
            Recovery Code
          </button>
        </div>

        {/* Notifications */}
        {error && (
          <div className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 flex-shrink-0" />
            {error}
          </div>
        )}
        {successMsg && (
          <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 flex-shrink-0" />
            {successMsg}
          </div>
        )}

        {/* Tab 1: Step-Up Verify */}
        {activeTab === "verify" && (
          <form onSubmit={handleVerifyTotp} className="space-y-4">
            <p className="text-xs text-slate-300">
              High-tier governance actions (Tier 2/3 financial mutation approval) require secondary TOTP verification.
            </p>

            <div>
              <label htmlFor="totp-code-input" className="block text-xs font-semibold text-slate-300 mb-1.5">
                6-Digit Authenticator Code:
              </label>
              <input
                id="totp-code-input"
                type="text"
                maxLength={6}
                value={totpCode}
                onChange={(e) => setTotpCode(e.target.value.replace(/\D/g, ""))}
                placeholder="123456"
                className="w-full text-center tracking-widest text-2xl font-mono py-2.5 bg-slate-950 border border-slate-700 rounded-lg text-indigo-300 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 rounded-lg text-xs font-medium text-slate-400 hover:bg-slate-800"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading || totpCode.length !== 6}
                className="px-4 py-2 rounded-lg text-xs font-bold bg-indigo-600 hover:bg-indigo-500 text-white disabled:opacity-50 transition"
              >
                {loading ? "Verifying..." : "Verify Code"}
              </button>
            </div>
          </form>
        )}

        {/* Tab 2: Enroll TOTP */}
        {activeTab === "setup" && (
          <div className="space-y-4 text-xs">
            {recoveryCodes.length === 0 ? (
              <>
                <p className="text-slate-300">
                  Scan the provisioning URI or copy the Base32 secret key into Google Authenticator or 1Password.
                </p>

                {setupData && (
                  <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-slate-400 font-mono text-[10px]">BASE32 SECRET KEY:</span>
                      <button
                        onClick={() => {
                          navigator.clipboard.writeText(setupData.secret);
                          setCopiedSecret(true);
                          setTimeout(() => setCopiedSecret(false), 2000);
                        }}
                        className="text-[10px] flex items-center gap-1 text-indigo-400 hover:text-indigo-300"
                      >
                        {copiedSecret ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        {copiedSecret ? "Copied" : "Copy Secret"}
                      </button>
                    </div>
                    <code className="block text-indigo-300 font-mono text-sm tracking-wider break-all">
                      {setupData.secret}
                    </code>
                  </div>
                )}

                <form onSubmit={handleActivateTotp} className="space-y-3 pt-2">
                  <div>
                    <label className="block font-semibold text-slate-300 mb-1">
                      Confirm 6-Digit Code from App:
                    </label>
                    <input
                      type="text"
                      maxLength={6}
                      value={setupVerificationCode}
                      onChange={(e) => setSetupVerificationCode(e.target.value.replace(/\D/g, ""))}
                      placeholder="000000"
                      className="w-full text-center text-lg font-mono py-2 bg-slate-950 border border-slate-700 rounded-lg text-slate-100 focus:outline-none focus:border-indigo-500"
                    />
                  </div>

                  <button
                    type="submit"
                    disabled={loading || setupVerificationCode.length !== 6}
                    className="w-full py-2.5 rounded-lg font-bold bg-indigo-600 hover:bg-indigo-500 text-white disabled:opacity-50 transition"
                  >
                    {loading ? "Activating..." : "Confirm & Issue Recovery Codes"}
                  </button>
                </form>
              </>
            ) : (
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-emerald-400 font-bold">
                  <CheckCircle2 className="w-4 h-4" />
                  Authenticator Active &bull; Emergency Recovery Codes (8 Total)
                </div>
                <p className="text-slate-400 text-[11px]">
                  Each code can be consumed once. Store these securely in an offline vault.
                </p>

                <div className="grid grid-cols-2 gap-2 bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono text-[11px] text-slate-300">
                  {recoveryCodes.map((code, idx) => (
                    <div key={idx} className="bg-slate-900 px-2 py-1 rounded border border-slate-800">
                      {code}
                    </div>
                  ))}
                </div>

                <button
                  type="button"
                  onClick={() => {
                    navigator.clipboard.writeText(recoveryCodes.join("\n"));
                    onClose();
                  }}
                  className="w-full py-2 rounded-lg font-bold bg-slate-800 hover:bg-slate-700 text-slate-200 transition"
                >
                  Copy All Codes &amp; Finish
                </button>
              </div>
            )}
          </div>
        )}

        {/* Tab 3: Emergency Recovery Code */}
        {activeTab === "recovery" && (
          <form onSubmit={handleConsumeRecovery} className="space-y-4">
            <p className="text-xs text-slate-300">
              Lost access to your authenticator app? Enter one of your single-use 12-character recovery codes.
            </p>

            <div>
              <label htmlFor="recovery-code-input" className="block text-xs font-semibold text-slate-300 mb-1.5">
                Recovery Code (e.g. abcd-efgh-ijkl):
              </label>
              <input
                id="recovery-code-input"
                type="text"
                value={recoveryCode}
                onChange={(e) => setRecoveryCode(e.target.value)}
                placeholder="xxxx-xxxx-xxxx"
                className="w-full text-center text-sm font-mono py-2.5 bg-slate-950 border border-slate-700 rounded-lg text-amber-300 focus:outline-none focus:border-amber-500"
              />
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 rounded-lg text-xs font-medium text-slate-400 hover:bg-slate-800"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading || !recoveryCode.trim()}
                className="px-4 py-2 rounded-lg text-xs font-bold bg-amber-600 hover:bg-amber-500 text-white disabled:opacity-50 transition"
              >
                {loading ? "Consuming..." : "Consume Recovery Code"}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};
