"""
RevPilot AI — Investigation Temporal Workflow and Activities Module
Conforms to docs/12-workflow-engine/TEMPORAL-WORKFLOW-SPEC.md §2–§8,
ADR-0002, and INVARIANT-REGISTRY.md (INV-WF-001, INV-WF-002, INV-TEN-001..003).
"""

from __future__ import annotations
from temporalio.worker import Replayer

from revpilot.modules.investigation.workflows.signals import (
    PauseInvestigationSignal,
    ResumeInvestigationSignal,
    CancelInvestigationSignal,
    InvestigationWorkflowInput,
    InvestigationState,
    InvestigationProgress,
)
from revpilot.modules.investigation.workflows.activities import (
    INVESTIGATION_WORKFLOW_QUEUE,
    INVESTIGATION_ANALYTICS_QUEUE,
    INVESTIGATION_RETRIEVAL_QUEUE,
    INVESTIGATION_AGENT_QUEUE,
    TRANSIENT_ACTIVITY_RETRY_POLICY,
    ValidateInvestigationScopeInput,
    ValidateInvestigationScopeResult,
    ValidateInvestigationScopeActivity,
    validate_investigation_scope_activity,
    GenerateInvestigationPlanInput,
    GenerateInvestigationPlanResult,
    GenerateInvestigationPlanActivity,
    generate_investigation_plan_activity,
    ExecuteReadOnlySqlCapabilityInput,
    ExecuteReadOnlySqlCapabilityResult,
    ExecuteReadOnlySqlCapabilityActivity,
    execute_read_only_sql_capability_activity,
    ExecuteGovernedRetrievalInput,
    ExecuteGovernedRetrievalResult,
    ExecuteGovernedRetrievalActivity,
    execute_governed_retrieval_activity,
    IngestTicketIntelligenceInput,
    IngestTicketIntelligenceResult,
    IngestTicketIntelligenceActivity,
    ingest_ticket_intelligence_activity,
    SynthesizeHypothesesInput,
    SynthesizeHypothesesResult,
    SynthesizeHypothesesActivity,
    synthesize_hypotheses_activity,
    VerifyEvidenceAndHypothesesInput,
    VerifyEvidenceAndHypothesesResult,
    VerifyEvidenceAndHypothesesActivity,
    verify_evidence_and_hypotheses_activity,
    PackageEvidenceBundleInput,
    PackageEvidenceBundleActivity,
    package_evidence_bundle_activity,
)
from revpilot.modules.investigation.workflows.investigation_workflow import (
    InvestigationWorkflow,
)

WorkflowReplayer = Replayer

__all__ = [
    "InvestigationWorkflow",
    "WorkflowReplayer",
    "PauseInvestigationSignal",
    "ResumeInvestigationSignal",
    "CancelInvestigationSignal",
    "InvestigationWorkflowInput",
    "InvestigationState",
    "InvestigationProgress",
    "INVESTIGATION_WORKFLOW_QUEUE",
    "INVESTIGATION_ANALYTICS_QUEUE",
    "INVESTIGATION_RETRIEVAL_QUEUE",
    "INVESTIGATION_AGENT_QUEUE",
    "TRANSIENT_ACTIVITY_RETRY_POLICY",
    "ValidateInvestigationScopeInput",
    "ValidateInvestigationScopeResult",
    "ValidateInvestigationScopeActivity",
    "validate_investigation_scope_activity",
    "GenerateInvestigationPlanInput",
    "GenerateInvestigationPlanResult",
    "GenerateInvestigationPlanActivity",
    "generate_investigation_plan_activity",
    "ExecuteReadOnlySqlCapabilityInput",
    "ExecuteReadOnlySqlCapabilityResult",
    "ExecuteReadOnlySqlCapabilityActivity",
    "execute_read_only_sql_capability_activity",
    "ExecuteGovernedRetrievalInput",
    "ExecuteGovernedRetrievalResult",
    "ExecuteGovernedRetrievalActivity",
    "execute_governed_retrieval_activity",
    "IngestTicketIntelligenceInput",
    "IngestTicketIntelligenceResult",
    "IngestTicketIntelligenceActivity",
    "ingest_ticket_intelligence_activity",
    "SynthesizeHypothesesInput",
    "SynthesizeHypothesesResult",
    "SynthesizeHypothesesActivity",
    "synthesize_hypotheses_activity",
    "VerifyEvidenceAndHypothesesInput",
    "VerifyEvidenceAndHypothesesResult",
    "VerifyEvidenceAndHypothesesActivity",
    "verify_evidence_and_hypotheses_activity",
    "PackageEvidenceBundleInput",
    "PackageEvidenceBundleActivity",
    "package_evidence_bundle_activity",
]
