"""
RevPilot AI — Canonical Data Module (Phase 01)
Public exports for canonical domain entities, enums, errors, and contracts.
Conforms to CANONICAL-DATA-MODEL.md and MODULE-BOUNDARIES.md.
"""

from revpilot.modules.canonical.enums import (
    CustomerSegment,
    AccountTier,
    CustomerStatus,
    OrderStatus,
    CancellationReason,
    DispatchStatus,
    ShipmentStatus,
    DelayReason,
    TicketTopic,
    TicketPriority,
    TicketSeverity,
    TicketStatus,
    FacilityType,
    MaintenanceEventType,
    MaintenanceType,
    MaintenanceSeverity,
    ContractType,
    ContractStatus,
    ClauseType,
    GatewayProvider,
    TransactionType,
    PaymentStatus,
    DataClassification,
    CurrencyCode,
    Currency,
)
from revpilot.modules.canonical.models import (
    CanonicalValidationError,
    TenantRequiredError,
    Customer,
    CustomerRecord,
    Order,
    OrderRecord,
    OrderLine,
    OrderLineRecord,
    Shipment,
    ShipmentRecord,
    SupportTicket,
    SupportTicketRecord,
    MaintenanceEvent,
    MaintenanceEventRecord,
    Contract,
    ContractRecord,
    ContractClause,
    ContractClauseRecord,
    PaymentReference,
    PaymentReferenceRecord,
)

__all__ = [
    # Enums
    "CustomerSegment",
    "AccountTier",
    "CustomerStatus",
    "OrderStatus",
    "CancellationReason",
    "DispatchStatus",
    "ShipmentStatus",
    "DelayReason",
    "TicketTopic",
    "TicketPriority",
    "TicketSeverity",
    "TicketStatus",
    "FacilityType",
    "MaintenanceEventType",
    "MaintenanceType",
    "MaintenanceSeverity",
    "ContractType",
    "ContractStatus",
    "ClauseType",
    "GatewayProvider",
    "TransactionType",
    "PaymentStatus",
    "DataClassification",
    "CurrencyCode",
    "Currency",
    # Errors
    "CanonicalValidationError",
    "TenantRequiredError",
    # Entities / Records
    "Customer",
    "CustomerRecord",
    "Order",
    "OrderRecord",
    "OrderLine",
    "OrderLineRecord",
    "Shipment",
    "ShipmentRecord",
    "SupportTicket",
    "SupportTicketRecord",
    "MaintenanceEvent",
    "MaintenanceEventRecord",
    "Contract",
    "ContractRecord",
    "ContractClause",
    "ContractClauseRecord",
    "PaymentReference",
    "PaymentReferenceRecord",
]
